### Makefile for cc, the UNIX C compiler

CC=cc
LD=ld

OBJS= src/symbols/lambdasymbol.o \
	src/symbols/variablesymbol.o \

all: ${OBJS}
	${LD} -o libracul.so ${OBJS}  

clean:
	rm -f libracul.so ${OBJS}

.c.o: ${CC} -I./src/symbols -c $<
