### Makefile for cc, the UNIX C compiler

CC=gcc
LD=ld

OBJS= src/symbols/lambdasymbol.o \
	src/symbols/variablesymbol.o \
	src/symbols/boundsymbol.o \
	src/symbols/freesymbol.o \
	src/api/api.symbols.o \

all: ${OBJS}
	${CC} -shared -o libracul.so ${OBJS}  

clean:
	rm -f libracul.so ${OBJS}

.c.o: ${CC} -I./src/symbols -I./src/api -c $<
